apiVersion: v1
kind: ConfigMap
metadata:
    name: mongoconfigmap
    namespace: test-ns
data:
    mongo_Host: mongosvcheadless
    mongo_User: devdb
---
apiVersion: v1
kind: Secret
metadata:
    name: mongosecret
    namespace: test-ns
type: Opaque
data:
    mongo_password: ZGV2ZGIxMjM=
---
apiVersion: v1
kind: Service
metadata:
    name: mongosvcheadless
    namespace: test-ns
spec:
    clusterIP: None
    selector:
        app: mongod
    ports:
      - port: 27017
        targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mongod
    namespace: test-ns
spec:
    selector:
        matchLabels:
            app: mongod
    serviceName: mongosvcheadless
    replicas: 2
    template:
        metadata:
            labels:
                app: mongod
        spec:
            containers:
              - name: mongod
                image: mongo:7.0
                resources:
                    requests:
                        cpu: 200m
                        memory: 256Mi
                    limits:
                        cpu: 500m
                        memory: 500Mi
                args:
                  - "mongod"
                  - "--replSet"
                  - "MainRepSet"
                  - "--bind_ip"
                  - "0.0.0.0"
                ports:
                  - containerPort: 27017
                volumeMounts:
                  - name: mongovolstate
                    mountPath: /data/db
    volumeClaimTemplates:
      - metadata:
            name: mongovolstate
        spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
                requests:
                    storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: splingdbdeployment
    namespace: test-ns
    labels:
        app: springdb
spec:
    selector:
        matchLabels:
            app: springdb
    replicas: 1
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            labels:
                app: springdb
        spec:
            containers:
              - name: springdb
                image: mistryvibe/spring-boot-app:13
                resources:
                    requests:
                        cpu: 200m
                        memory: 256Mi
                    limits:
                        cpu: 300m
                        memory: 500Mi
                env:
                  - name: MONGO_DB_HOSTNAME
                    valueFrom:
                        configMapKeyRef:
                            name: mongoconfigmap
                            key: mongo_Host
                  - name: MONGO_DB_USERNAME
                    valueFrom:
                        configMapKeyRef:
                            name: mongoconfigmap
                            key: mongo_User
                  - name: MONGO_DB_PASSWORD
                    valueFrom:
                        secretKeyRef:
                            name: mongosecret
                            key: mongo_password
                ports:
                  - containerPort: 8080
                    name: springdb
---
apiVersion: v1
kind: Service
metadata:
    name: springsvc
    namespace: test-ns
spec:
    selector:
        app: springdb
    type: NodePort
    ports:
      - port: 8080
        targetPort: 8080
        nodePort: 30000
